package com.bahamaeatsdriver.model_class.driver_tips_earning

data class Order(
    val address: String,
    val addressId: String,
    val cartFee: String,
    val createdAt: String,
    val deliveryFee: Double,
    val foodPrice: String,
    val id: Int,
    val isDelivery: String,
    val latitude: String,
    val longitude: String,
    val netAmount: String,
    val orderDate: String,
    val orderType: String,
    val paymentMethod: Int,
    val paymentStatus: Int,
    val preparationTime: String,
    val promoCode: String,
    val promoDiscount: String,
    val restaurantId: Int,
    val scheduledDatetime: String,
    val scheduledTimestamp: String,
    val serviceFee: Double,
    val serviceFeePercentage: String,
    val specialRequest: String,
    val status: Int,
    val tax: String,
    val taxPercentage: String,
    val tip: Double,
    val totalAmount: String,
    val transactionId: Int,
    val transactionNo: String,
    val updatedAt: String,
    val userId: Int
)